### ISSUE TITLE
Publish to npm registry

### ISSUE THREAD

**Issue by Glavin001** [sketchpunklabs/manipulator3d#2]
@sketchpunk do you plan to publish this as a package to npm?

Related to https://github.com/sketchpunklabs/manipulator3d/pull/1 and https://github.com/pmndrs/drei/pull/933#discussion_r889636687

**Comment by sketchpunk** [comment]
I was thinking about it down the line if there was a need for it. I just checked and "manipulator3d" is an available package name that I can use so that's a big plus. I guess if we work out that pr, I can try to set it up on npm.

**Comment by sketchpunk** [comment]
Done.
