### ISSUE TITLE
WARNING: Multiple instances of Three.js being imported. 

### ISSUE THREAD

**Issue by drcmda** [sketchpunklabs/manipulator3d#3]
when this package is pulled in it throws the warning above. this happens because three is declared as a dependency, so the bundler is forced to install it as node_modules/manipulator3d/node_modules/three, which is unusual for a package as it creates resolution conflicts:

```json
    "dependencies": {
        "three" : "^0.138.2"
    },
```

the correct config would be:

```json
    "peerDependencies": {
        "three" : "^0.138.2"
    },
```

thank you for such a useful control! :-)

**Comment by Glavin001** [comment]
Will be fixed with https://github.com/sketchpunklabs/manipulator3d/pull/6

**Comment by sketchpunk** [comment]
Change applied to v0.0.0.6, live on npm.

**Comment by Glavin001** [comment]
Fixed with https://github.com/sketchpunklabs/manipulator3d/commit/758b851103b24e75d7c5450d1fb27f96e76fcf1a
