### ISSUE TITLE
Add method to clean up (e.g. unsubscribe from events)

### ISSUE THREAD

**Issue by Glavin001** [sketchpunklabs/manipulator3d#4]
## Why?

So this can be destroyed and cleaned up correctly.

### Solution

Unsubscribe these events and potentially others:  https://github.com/sketchpunklabs/manipulator3d/blob/01ff7a1255c2fbc0e3adfb9ef1332b2fbdc27a12/src/Manipulator3D.js#L72-L107

**Comment by Glavin001** [comment]
Fixed with https://github.com/sketchpunklabs/manipulator3d/pull/7

**Comment by sketchpunk** [comment]
changes related applied to v0.0.0.6 and live on npm.

**Comment by Glavin001** [comment]
Fixed with https://github.com/sketchpunklabs/manipulator3d/commit/f84f37749b2a270ef6df3d3192374440a04880eb
